apiVersion: v2
name: aios
description: A Helm chart for deploying AIOS in Kubernetes.
maintainers:
  - name: LEFTSHIFT ONE Software GmbH
    url: https://www.leftshift.one
    email: contact@leftshift.one

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.3.0"

dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 11.4.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: rabbitmq.enabled
  - name: keycloak
    version: 12.3.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: keycloak.enabled
  - name: kube-prometheus-stack
    alias: kubeprometheusstack
    version: 44.4.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeprometheusstack.enabled
  - name: loki-stack
    alias: lokistack
    version: 2.9.9
    repository: https://grafana.github.io/helm-charts
    condition: lokistack.enabled
  - name: grafana-agent-operator
    alias: grafanaagentoperator
    version: 0.2.12
    repository: https://grafana.github.io/helm-charts
    condition: grafanaagentoperator.enabled
  - name: keda
    version: 2.10.2
    repository: https://kedacore.github.io/charts
    condition: keda.enabled
