{{- if and .Values.emqx.enabled .Values.emqx.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.emqx.envFromSecret }}
  labels:
  {{- include "emqx.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.emqx.envFromSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  ADMIN_USERNAME: {{ get $existingSecretData "ADMIN_USERNAME" }}
  ADMIN_PASSWORD: {{ get $existingSecretData "ADMIN_PASSWORD" }}
  ADMIN_DASHBOARD_USERNAME: {{ get $existingSecretData "ADMIN_DASHBOARD_USERNAME" }}
  ADMIN_DASHBOARD_PASSWORD: {{ get $existingSecretData "ADMIN_DASHBOARD_PASSWORD" }}
  EMQX_AUTH__MNESIA__1__LOGIN: {{ get $existingSecretData "EMQX_AUTH__MNESIA__1__LOGIN" }}
  EMQX_AUTH__MNESIA__1__PASSWORD: {{ get $existingSecretData "EMQX_AUTH__MNESIA__1__PASSWORD" }}
  EMQX_DASHBOARD__DEFAULT_USER__LOGIN: {{ get $existingSecretData "EMQX_DASHBOARD__DEFAULT_USER__LOGIN" }}
  EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: {{ get $existingSecretData "EMQX_DASHBOARD__DEFAULT_USER__PASSWORD" }}
  {{- else }}
  {{- $adminUser := default "admin" .Values.emqx.config.EMQX_AUTH__MNESIA__1__LOGIN }}
  {{- $adminPassword := default (include "aios.randomPassword" .) .Values.emqx.config.EMQX_AUTH__MNESIA__1__PASSWORD }}
  {{- $adminDashboardUser := default "admin" .Values.emqx.config.EMQX_DASHBOARD__DEFAULT_USER__LOGIN }}
  {{- $adminDashboardPassword := default (include "aios.randomPassword" .) .Values.emqx.config.EMQX_DASHBOARD__DEFAULT_USER__PASSWORD }}
  ADMIN_USERNAME: {{ b64enc $adminUser }}
  ADMIN_PASSWORD: {{ b64enc $adminPassword }}
  ADMIN_DASHBOARD_USERNAME: {{ b64enc $adminDashboardUser }}
  ADMIN_DASHBOARD_PASSWORD: {{ b64enc $adminDashboardPassword }}
  EMQX_AUTH__MNESIA__1__LOGIN: {{ b64enc $adminUser }}
  EMQX_AUTH__MNESIA__1__PASSWORD: {{ b64enc $adminPassword }}
  EMQX_DASHBOARD__DEFAULT_USER__LOGIN: {{ b64enc $adminDashboardUser }}
  EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: {{ b64enc $adminDashboardPassword }}
  {{- end }}
  EMQX_AUTH__HTTP__AUTH_REQ: {{ b64enc (printf "%s/api/v1/authenticate/jwt" (include "aios.url-internal" .)) }}
{{- end -}}
