{{- if and .Values.emqx.enabled .Values.emqx.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "emqx.serviceAccountName" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "emqx.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "emqx.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}