{{- if and .Values.emqx.enabled .Values.emqx.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emqx.serviceAccountName" . }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
  {{- with .Values.emqx.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
