{{- if and .Values.emqx.enabled .Values.emqx.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "emqx.serviceAccountName" . }}-role
rules:
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get", "watch", "list" ]
{{- end }}
