{{- if and .Values.kubeprometheusstack.enabled (and .Values.kubeprometheusstack.grafana.enabled .Values.kubeprometheusstack.grafana.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeprometheusstack.grafana.admin.existingSecret }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.kubeprometheusstack.grafana.admin.existingSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  admin-user: {{ get $existingSecretData "admin-user" }}
  admin-password: {{ get $existingSecretData "admin-password" }}
  {{- else }}
  admin-user: {{ b64enc "admin" }}
  admin-password: {{ b64enc (include "aios.randomPassword" .) }}
  {{- end }}
{{- end }}
