{{- if and .Values.grafanaagentoperator.enabled .Values.grafanaagentoperator.grafanaAgent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aios.fullname" . }}-grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aios.fullname" . }}-grafana-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Values.grafanaagentoperator.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end}}
