{{- if and .Values.keycloak.enabled (and .Values.keycloak.extraEnvVarsSecret .Values.keycloak.initContainers) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.extraEnvVarsSecret }}-init
  labels:
  {{- include "aios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  KEYCLOAK_INIT_DATABASE_NAME: {{ b64enc .Values.postgresql.postgresqlDatabase }}
  KEYCLOAK_INIT_DATABASE_USER: {{ b64enc "postgres" }}
{{- end -}}
