{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.themeConfigmapName }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
binaryData:
  {{- $files := .Files }}
  {{- range $path, $_ := .Files.Glob "themes/keycloak-aios/**" }}
  {{ $path | replace "/" "." }}: {{ $files.Get $path | b64enc }}
  {{- end }}
{{- end }}
