{{- if .Values.keycloak.passwordsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.passwordsSecretName }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.keycloak.passwordsSecretName) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  admin-user: {{ get $existingSecretData "admin-user" }}
  admin-password: {{ get $existingSecretData "admin-password" }}
  grafana-client-secret: {{ get $existingSecretData "grafana-client-secret" }}
  {{- else }}
  {{- if hasKey .Values.keycloak.config "KEYCLOAK_ADMIN" }}
  admin-user: {{ b64enc .Values.keycloak.config.KEYCLOAK_ADMIN }}
  {{- else }}
  admin-user: {{ b64enc "admin" }}
  {{- end }}
  {{- if hasKey .Values.keycloak.config "KEYCLOAK_ADMIN_PASSWORD" }}
  admin-password: {{ b64enc .Values.keycloak.config.KEYCLOAK_ADMIN_PASSWORD }}
  {{- else }}
  admin-password: {{ b64enc (include "aios.randomPassword" .) }}
  {{- end }}
  grafana-client-secret: {{ b64enc (include "aios.randomPassword" .) }}
  {{- end }}
{{- end -}}
