{{- if and .Values.keycloak.enabled .Values.keycloak.extraEnvVarsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.extraEnvVarsSecret }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.keycloak.extraEnvVarsSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  KEYCLOAK_DATABASE_HOST: {{ $existingSecretData.KEYCLOAK_DATABASE_HOST }}
  KEYCLOAK_DATABASE_PORT: {{ $existingSecretData.KEYCLOAK_DATABASE_PORT }}
  KEYCLOAK_DATABASE_NAME: {{ $existingSecretData.KEYCLOAK_DATABASE_NAME }}
  KC_DB: {{ $existingSecretData.KC_DB }}
  KC_DB_SCHEMA: {{ $existingSecretData.KC_DB_SCHEMA }}
  KC_DB_URL: {{ $existingSecretData.KC_DB_URL }}
  KC_DB_USERNAME: {{ $existingSecretData.KC_DB_USERNAME }}
  KC_DB_PASSWORD: {{ $existingSecretData.KC_DB_PASSWORD }}
  {{- else }}
  {{- $jdbcHost := printf "%s-postgresql" (include "aios.fullname" .) -}}
  {{- $jdbcPort := .Values.postgresql.primary.service.ports.postgresql | toString -}}
  {{- $jdbcDatabase := "keycloak" -}}
  {{- if hasKey .Values.app.config "AIOS_JDBC_URL" }}
  {{- $parsedUrl := urlParse (.Values.app.config.AIOS_JDBC_URL | replace "jdbc:" "") }}
  {{- $rawHost := splitList ":" (get $parsedUrl "host") }}
  {{- $jdbcDatabase = trimPrefix "/" (get $parsedUrl "path") }}
  {{- $jdbcHost = first $rawHost }}
  {{- $rawPort := rest $rawHost }}
  {{- if $rawPort }}
  {{- $jdbcPort = first $rawPort }}
  {{- else }}
  {{- $jdbcPort = "5432" }}
  {{- end }}
  {{- end }}
  KEYCLOAK_DATABASE_HOST: {{ b64enc $jdbcHost }}
  KEYCLOAK_DATABASE_PORT: {{ b64enc $jdbcPort }}
  KEYCLOAK_DATABASE_NAME: {{ b64enc $jdbcDatabase }}
  KC_DB: {{ b64enc "postgres" }}
  KC_DB_SCHEMA: {{ b64enc "public" }}
  KC_DB_URL: {{ b64enc (printf "jdbc:postgresql://%s:%s/%s" $jdbcHost $jdbcPort $jdbcDatabase) }}
  KC_DB_USERNAME: {{ b64enc "keycloak" }}
  KC_DB_PASSWORD: {{ b64enc (include "aios.randomPassword" .) }}
  {{- end }}
{{- end -}}
