{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aios.serviceAccountName" . }}-clusterrole
  labels:
  {{- include "aios.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "limitranges"
      - "resourcequotas"
      - "configmaps"
      - "secrets"
      - "pods"
      - "pods/status"
      - "pods/log"
      - "services"
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments"
      - "statefulsets"
      - "replicasets"
      - "jobs"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "servicemonitors"
      - "podmonitors"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
{{- end }}