{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aios.serviceAccountName" . }}-role
  labels:
  {{- include "aios.labels" . | nindent 4 }}
rules:
# tag::permissions[]
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "patch"
  - apiGroups:
      - "apps"
    resources:
      - "replicasets"
    verbs:
      - "get"
      - "list"
# end::permissions[]
{{- end }}