{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aios.serviceAccountName" . }}-rolebinding
  labels:
  {{- include "aios.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aios.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "aios.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}