{{- if and .Values.serviceAccount.create (not .Values.serviceAccount.installClusterWidePermissions) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aios.serviceAccountName" . }}-namespace-mode-rolebinding
  labels:
  {{- include "aios.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aios.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aios.serviceAccountName" . }}-namespace-mode-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}