{{- if and .Values.serviceAccount.create .Values.serviceAccount.installClusterWidePermissions -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aios.serviceAccountName" . }}-namespace-mode-clusterrole
  labels:
  {{- include "aios.labels" . | nindent 4 }}
rules:
  {{- if .Values.serviceAccount.clusterRoleRules }}
  {{- toYaml .Values.serviceAccount.clusterRoleRules | nindent 4 }}
  {{- else }}
# tag::permissions[]
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
      - "patch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "limitranges"
      - "resourcequotas"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
      - "pods"
      - "services"
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "pods/status"
      - "pods/log"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments"
      - "statefulsets"
      - "replicasets"
      - "jobs"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments/status"
      - "statefulsets/status"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - "events.k8s.io"
    resources:
      - "events"
    verbs:
      - "get"
      - "watch"
      - "list"
# end::permissions[]
{{- if or .Values.kubeprometheusstack.enabled .Values.grafanaagentoperator.enabled }}
# tag::prometheus_permissions[]
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "servicemonitors"
      - "podmonitors"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
  - apiGroups:
      - "monitoring.grafana.com"
    resources:
      - "grafanaagents"
      - "metricsinstances"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
# end::prometheus_permissions[]
{{- end }}
{{- if .Values.keda.enabled }}
# tag::keda_permissions[]
  - apiGroups:
      - "keda.sh"
    resources:
      - "scaledobjects"
      - "triggerauthentications"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "deletecollection"
      - "update"
      - "patch"
# end::keda_permissions[]
{{- end }}
{{- end }}
{{- end }}