{{- if and .Values.serviceAccount.create .Values.serviceAccount.installClusterWidePermissions -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aios.serviceAccountName" . }}-namespace-mode-clusterrolebinding
  labels:
  {{- include "aios.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aios.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aios.serviceAccountName" . }}-namespace-mode-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}