{{- if .Values.app.smtpConfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.smtpConfigSecretName }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.app.smtpCredentialsSecretName }}
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.app.smtpCredentialsSecretName) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  AIOS_SMTP_USER: {{ get $existingSecretData "AIOS_SMTP_USER" }}
  AIOS_SMTP_PASSWORD: {{ get $existingSecretData "AIOS_SMTP_PASSWORD" }}
  {{- end }}
  {{- else }}
  AIOS_SMTP_USER: {{ b64enc (default "please-set-user" .Values.app.config.AIOS_SMTP_USER) }}
  AIOS_SMTP_PASSWORD: {{ b64enc (default "please-set-password" .Values.app.config.AIOS_SMTP_PASSWORD) }}
  {{- end }}
  AIOS_SMTP_FROM_ADDRESS: {{ b64enc (default "aios@local" .Values.app.config.AIOS_SMTP_FROM_ADDRESS) }}
  AIOS_SMTP_FROM_NAME: {{ b64enc (default "AIOS" .Values.app.config.AIOS_SMTP_FROM_NAME) }}
  AIOS_SMTP_REPLY_ADDRESS: {{ b64enc (default "aios@local" .Values.app.config.AIOS_SMTP_REPLY_ADDRESS) }}
  AIOS_SMTP_HOST: {{ b64enc (default "localhost" .Values.app.config.AIOS_SMTP_HOST) }}
  AIOS_SMTP_PORT: {{ b64enc (default "25" .Values.app.config.AIOS_SMTP_PORT) }}
  AIOS_SMTP_AUTH: {{ b64enc (default "true" .Values.app.config.AIOS_SMTP_AUTH) }}
  AIOS_SMTP_STARTTLS: {{ b64enc (default "true" .Values.app.config.AIOS_SMTP_STARTTLS) }}
{{- end -}}
