apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.urlsConfigMapName }}
  labels:
  {{- include "aios.labels" . | nindent 4 }}
data:
  aios-url: {{ (include "aios.url" .) | quote }}
  aios-internal-url: {{ (include "aios.url-internal" .) | quote }}
  aios-realm-redirect-url: {{ printf "%s/*" (include "aios.url" .) | quote }}
  keycloak-url: {{ printf "%s" (include "aios.keycloak.url" .) }}
  keycloak-internal-url: {{ printf "%s" (include "aios.keycloak.url-internal" .) }}
  {{- $amqpProtocol := "ws" }}
  {{- if .Values.ingress.tls }}
  {{- $amqpProtocol = "wss" }}
  {{- end }}
  {{- $amqpHost := "localhost" }}
  {{- if .Values.ingress.hosts }}
  {{- $amqpHost = (first .Values.ingress.hosts).host }}
  {{- end }}
  {{- $amqpPath := "/amqp" }}
  {{- $amqpUrl := printf "%s://%s%s" $amqpProtocol $amqpHost $amqpPath }}
  amqp-url: {{ $amqpUrl }}
  grafana-url: {{ include "aios.grafana.url" . }}
  grafana-internal-url: {{ include "aios.grafana.url-internal" . }}
  grafana-realm-redirect-url: {{ printf "%s/*" (include "aios.grafana.url" .) }}
  loki-internal-url: {{ include "aios.grafana.loki.url" . }}
  prometheus-internal-url: {{ include "aios.prometheus.url" . }}
