{
 "title": "AIOS Services",
 "tags": [ "AIOS" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{aios_dev_service_id!=\"\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{app_kubernetes_io_name=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\", envoy_cluster_name!=\"aios\"}[$__rate_interval])",
     "legendFormat": "{{envoy_cluster_name}} (v{{aios_dev_service_version}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successes (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\", envoy_response_code_class=\"2\", envoy_cluster_name!=\"aios\"}[$__rate_interval])",
     "legendFormat": "{{envoy_cluster_name}} (v{{aios_dev_service_version}})"
    }
   ]
  },
  {
   "title": "Saturation (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[5m]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Errors (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\", envoy_response_code_class=\"5\", envoy_cluster_name!=\"aios\"}[$__rate_interval])",
     "legendFormat": "{{envoy_cluster_name}} (v{{aios_dev_service_version}})"
    }
   ]
  },
  {
   "title": "Errors (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\", envoy_response_code_class=\"4\", envoy_cluster_name!=\"aios\"}[$__rate_interval])",
     "legendFormat": "{{envoy_cluster_name}} (v{{aios_dev_service_version}})"
    }
   ]
  },
  {
   "title": "Saturation (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Redirects (3xx)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{namespace=\"$namespace\", app_kubernetes_io_name=\"$service\", envoy_response_code_class=\"3\", envoy_cluster_name!=\"aios\"}[$__rate_interval])",
     "legendFormat": "{{envoy_cluster_name}} (v{{aios_dev_service_version}})"
    }
   ]
  }
 ]
}