{{- if and .Values.postgresql.enabled .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.existingSecret }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
  postgresql-postgres-password: {{ get $existingSecretData "postgresql-postgres-password" }}
  postgresql-password: {{ get $existingSecretData "postgresql-password" }}
  {{- else }}
  postgresql-postgres-password: {{ b64enc (include "oops.randomPassword" .) }}
  postgresql-password: {{ b64enc (include "oops.randomPassword" .) }}
  {{- end }}
{{- end -}}
