apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oops.serviceAccountName" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "oops.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "oops.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
