apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oops.serviceAccountName" . }}-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
