apiVersion: v1
kind: Service
metadata:
  name: {{ include "oops.fullname" . }}
  labels:
    {{- include "oops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: java-debug
      protocol: TCP
      name: java-debug
  selector:
    {{- include "oops.selectorLabels" . | nindent 4 }}
