{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "intent-detection.fullname" . }}
  {{- if .Values.podMonitor.namespace }}
  namespace: {{ .Values.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "intent-detection.labels" . | nindent 4 }}
    release: {{ $.Release.Name | quote }} # to be matched by podMonitorSelectorNilUsesHelmValues of the kube-prometheus-stack
    {{- range $key, $val := .Values.podMonitor.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - path: {{ .Values.podMonitor.path }}
      port: {{ .Values.podMonitor.port }}
      interval: {{ .Values.podMonitor.interval | quote }}
  podTargetLabels:
    {{- range .Values.podMonitor.additionalPodTargetLabels }}
    - {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "intent-detection.selectorLabels" . | nindent 6 }}
{{- end}}
