apiVersion: v1
kind: Service
metadata:
  name: {{ include "intent-detection.fullname" . }}-app
  labels:
    application: {{ include "intent-detection.name" . }}
    {{- include "intent-detection.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ (first (first .Values.ingress.hosts).paths).port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intent-detection.selectorLabels" . | nindent 4 }}
