{{- if .Values.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  version: {{ .Values.elasticsearch.version | quote }}
  nodeSets:
    - name: {{ .Release.Name }}
      count: {{ .Values.elasticsearch.replicas }}
      {{- with .Values.elasticsearch.config }}
      config:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.elasticsearch.podTemplate }}
      podTemplate:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.elasticsearch.volumeClaimTemplates }}
      volumeClaimTemplates:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
