{{- if and .Values.minio.enabled .Values.minio.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.auth.existingSecret }}
  labels:
  {{- include "semantic-search.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.minio.auth.existingSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
    {{- range $k, $v := $existingSecretData }}
  {{ $k }}: {{ $v }}
    {{- end }}
  {{- else }}
  root-user: {{ default "admin" .Values.minio.auth.rootUser }}
  root-password: {{ b64enc (include "semantic-search.randomPassword" .) }}
  {{- end }}
{{- end -}}
