{{- if and .Values.minio.enabled .Values.minio.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first .Values.minio.users).existingSecret }}
  labels:
  {{- include "semantic-search.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (first .Values.minio.users).existingSecret) }}
  {{- if $existingSecret }}
  {{- $existingSecretData := $existingSecret.data }}
    {{- range $k, $v := $existingSecretData }}
  {{ $k }}: {{ $v }}
    {{- end }}
  {{- else }}
    {{- range .Values.minio.users }}
  {{ .accessKey }}Password: {{ b64enc (include "semantic-search.randomPassword" .) }}
    {{- end }}
  {{- end }}
{{- end -}}
