apiVersion: v2
name: semantic-search
description: A Helm chart for Kubernetes
maintainers:
  - name: LEFTSHIFT ONE Software GmbH
    url: https://www.leftshift.one
    email: contact@leftshift.one

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0


# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.1.0


dependencies:
  - name: semantic-search-indexer
    version: 0.1.0

    repository: file://../../../indexer/build/helm/semantic-search-indexer
    condition: semantic-search-indexer.enabled
  - name: semantic-search-searcher
    version: 0.1.0

    repository: file://../../../searcher/build/helm/semantic-search-searcher
    condition: semantic-search-searcher.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: prometheus-elasticsearch-exporter
    version: 4.13.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-elasticsearch-exporter.enabled
  - name: minio
    version: 4.0.8
    repository: https://charts.min.io
    condition: minio.enabled
